### ISSUE TITLE
建议作者删除.idea目录

### ISSUE THREAD

**Issue by tianshaokai** [mCyp/Orient-Ui#1]
如题

**Comment by mCyp** [comment]
已经删除，谢啦~

**Comment by tianshaokai** [comment]
嗯 最好修改一下 .gitignore 文件 防止以后继续提交.idea 目录
目前同步代码 就会出现一些自动修改冲突

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TeaOf <notifications@github.com&gt;
发送时间: 2019年10月10日 22:56
收件人: mCyp/Orient-Ui <Orient-Ui@noreply.github.com&gt;
抄送: 田绍凯 <1575640686@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mCyp/Orient-Ui] 建议作者删除.idea目录 (#1)




已经删除，谢啦~

**Comment by mCyp** [comment]
还有什么要删除的吗？

**Comment by tianshaokai** [comment]
看了一下作者的提交历史 删除了.gitignore文件，这个文件是不要删除的， 这个文件的作用是在提交时 告诉git你忽略哪些文件不提交
我昨晚的意思是你修改一下这个文件的配置 忽略整个.idea 目录



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TeaOf <notifications@github.com&gt;
发送时间: 2019年10月11日 06:46
收件人: mCyp/Orient-Ui <Orient-Ui@noreply.github.com&gt;
抄送: 田绍凯 <1575640686@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mCyp/Orient-Ui] 建议作者删除.idea目录 (#1)




还有什么要删除的吗？

**Comment by mCyp** [comment]
... 好吧，自己一直是独立开发，也没注意过这些东西，这几天抽空学一下，哈哈，感谢~

**Comment by tianshaokai** [comment]
哈哈可以加一下微信交流学习微信： kai157564



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TeaOf <notifications@github.com&gt;
发送时间: 2019年10月11日 08:37
收件人: mCyp/Orient-Ui <Orient-Ui@noreply.github.com&gt;
抄送: 田绍凯 <1575640686@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mCyp/Orient-Ui] 建议作者删除.idea目录 (#1)




... 好吧，自己一直是独立开发，也没注意过这些东西，这几天抽空学一下，哈哈，感谢~
